meta_product_name: "Get Local"
meta_title: "Get Local - Get Local and Fresh Products around you"
meta_description: "An app to search local store, buy fresh and organics products around you"
meta_image: "cover.jpeg" # should exist in `app/assets/images/`
